version: 2

release:
  replace_existing_artifacts: true

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    binary: getoken
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/tomozo6/getoken/cmd.Version=v{{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: tomozo6
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/tomozo6/getoken"
    description: "getoken is a Go CLI to fetch Firebase Identity Toolkit ID tokens."
